version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin
  MYSQL_DATABASE: vgdb
  REACT_APP_SERVER_PORT: 8000
  MONGO_USERNAME: root
  MONGO_PASSWORD: root
  MONGO_HOSTNAME: localhost
  MONGO_PORT: 27017
  MONGO_DB: vgdb

services:
  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongodb
    restart: unless-stopped
    environment:
      <<: *common-variables
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
  server:
    build: ./server
    depends_on:
      - mongo
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mongo
    command: npm start
  client2:
    build: ./client2
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client2/src:/app/src
    links:
      - server
    stdin_open: true
    command: npm start
volumes:
  dbdata:
